### ISSUE TITLE
struct.error: unpack requires a buffer of XXX bytes

### ISSUE THREAD

**Issue by VG154** [EgorKin/Novatek-FW-info#1]
When I try to open this file, the script crashes with the following error:

NVTPACK_FW_HDR2 found
NVTPACK_FW_HDR2_VERSION found
Found 5 partitions
Firmware file size 6 092 236 bytes
Traceback (most recent call last):
  File "./NTKFWinfo.py", line 2308, in <module>
    main()
  File "./NTKFWinfo.py", line 2103, in main
    CRC_FW = MemCheck_CalcCheckSum16Bit(in_file, 0, total_file_size, 0x24)
  File "./NTKFWinfo.py", line 291, in MemCheck_CalcCheckSum16Bit
    for chunk in struct.unpack("<%sH" % num_words, fread[0:num_words*2]):
**struct.error: unpack requires a buffer of 6092236 bytes**
[FWPRE.zip](https://github.com/EgorKin/Novatek-FW-info/files/11397295/FWPRE.zip)

**Comment by VG154** [comment]
Sorry, FW file was corrupted.
